### ISSUE TITLE
Make doesn't build LDC yet

### ISSUE THREAD

**Issue by quickfur** [opendlang/opend#11]
I know this is probably in the works, but just documenting the current state of things.

**Comment by adamdruppe** [comment]
I'm not sure I want it to... ldc's thing is a bit separate, the way i built it is

```
mkdir /tmp/ldc-build
cd /tmp/ldc-build
cmake ~/opend/ldc
make
```

and i think i like it like that.

**Comment by adamdruppe** [comment]
Of course, the top-level makefile could perhaps do that too just im more planning on documenting that than integrating it per se

**Comment by quickfur** [comment]
I was just thinking it would be a nice change from upstream to have `make` just do *everything* for you, instead of having to read a wiki page and manually type in 15 obscure CLI commands just to get a working toolchain.

It's no biggie, of course, but at least the above steps should be documented. I couldn't find any information except on the LDC wiki, which has a whole bunch of obscure steps.  Just putting this in the README or something would go a long way in making this more accessible to people.

**Comment by adamdruppe** [comment]
I've been taking live notes on teh website (at least when i don't typo it and lead to a html validation error lol)

https://dpldocs.info/opend/start.html

but yeah a `make ldc` target could alway go over and do that too.

**Comment by denizzzka** [comment]
Debian 12:
```
$ make ldc
[...]
[ 50%] Linking CXX executable ../../../bin/ldc-profgen
/usr/bin/ld: CMakeFiles/ldc-profgen.dir/CSPreInliner.cpp.o: in function `llvm::sampleprof::CSPreInliner::processFunction(llvm::StringRef)':
CSPreInliner.cpp:(.text+0xc0d): undefined reference to `llvm::SampleContextTracker::getContextString[abi:cxx11](llvm::sampleprof::FunctionSamples const&) const'
/usr/bin/ld: CSPreInliner.cpp:(.text+0xec8): undefined reference to `llvm::SampleContextTracker::getContextString[abi:cxx11](llvm::sampleprof::FunctionSamples const&) const'
/usr/bin/ld: CMakeFiles/ldc-profgen.dir/CSPreInliner.cpp.o: in function `llvm::sampleprof::CSPreInliner::run()::{lambda(llvm::SampleContextTracker&, bool)#1}::operator()(llvm::SampleContextTracker&, bool) const':
CSPreInliner.cpp:(.text+0x1070): undefined reference to `llvm::SampleContextTracker::getContextString[abi:cxx11](llvm::ContextTrieNode*) const'
collect2: error: ld returned 1 exit status
make[3]: *** [tools/ldc-profgen/ldc-profgen-16.0/CMakeFiles/ldc-profgen.dir/build.make:177: bin/ldc-profgen] Error 1
make[3]: Leaving directory '/home/denizzz/Dev/opend/ldc-build'
make[2]: *** [CMakeFiles/Makefile2:555: tools/ldc-profgen/ldc-profgen-16.0/CMakeFiles/ldc-profgen.dir/all] Error 2
make[2]: Leaving directory '/home/denizzz/Dev/opend/ldc-build'
make[1]: *** [Makefile:166: all] Error 2
make[1]: Leaving directory '/home/denizzz/Dev/opend/ldc-build'
make: *** [Makefile:105: ldc] Error 2
```

**Comment by adamdruppe** [comment]
gonna close since the PR was merged to add it
