### ISSUE TITLE
ARM support planned? RISC-V?

### ISSUE THREAD

**Issue by mconger** [opendlang/opend#73]
Just discovered OpenD today. It looks like there’s no ARM architecture support. Given that OpenD just began six months ago I understand there’s a lot to do and prioritize. That said, ARM is poised to be a big player this year in the laptop space (not talking about Apple Silicon.) 

I’m just curious if there are future plans for additional architectures.

RISC-V is trying to be a player as well and given the open source nature of that processor core design I would hope OpenD would at least consider it for the future.

I’m excited!

**Comment by adamdruppe** [comment]
It's already there! Use the ldc2 program from the CI download or `make ldc` with a proper llvm to compile it yourself.

**Comment by adamdruppe** [comment]
https://github.com/opendlang/opend/releases/tag/CI

has the auto-built packages. some of them run on arm, all of them can potentially cross compile (but you have to set up some stuff yourself anyway so it isn't exactly turnkey)

**Comment by adamdruppe** [comment]
gonna close since the ci is working for this now pretty reliably
