### ISSUE TITLE
`@implicit this` causes compiler crash

### ISSUE THREAD

**Issue by GrimMaple** [opendlang/opend#81]
Provided minimal example causes a compiler crash with the following message: `Exception Code: 0xC00000FD`

If a `this(ref A other)` constructor is removed, the code compiles. I suspect the compiler is unable to identify what constructor to use, as they both fit for `o = new Object();`

```d
struct A
{
    @implicit this(Object t) { }

    this(ref A other) { }
}
class Z
{
    A o = new Object();;
}
```

**Comment by adamdruppe** [comment]
ok i see the cause, the code that checks for implicit things is wrongly triggered here and sends it down infinite recursion

have a hack fix ready will see about posting a real fix later today.

**Comment by adamdruppe** [comment]
this should be fixed in the latest build

**Comment by GrimMaple** [comment]
Confirmed working
