### ISSUE TITLE
prolly a copy paste residuum 

### ISSUE THREAD

**Issue by zero-vector** [opendlang/opend#83]
https://github.com/opendlang/opend/blob/0f83714c030b39a9acd849a2eb8d034e06d34832/compiler/src/dmd/dsymbolsem.d#L8056

**Comment by adamdruppe** [comment]
what's the problem this makes?

**Comment by zero-vector** [comment]
```d
pragma(explicit_gc, 1, 2)`
```

``` 
Error: one boolean expression expected for `pragma(inline)`, not 2
```
should be `explicit_gc`, that is all

**Comment by adamdruppe** [comment]
oooooooooooooh i see ok will fix in the next push

**Comment by adamdruppe** [comment]
fix up now
